export interface ResultData {
    A?:number;
    B?:number;
    C?:number;
    D?:number;
    E?:number;
    F?:number;
    G?:number;
    H?:number;
    I?:number;
    J?:number;
    K?:number;
    L?:number;
    M?:number;
    N?:number;
    O?:number;
    P?:number;
    Q?:number;
    R?:number;
    S?:number;
    T?:number;
    U?:number;
    V?:number;
    W?:number;
    X?:number;
    Y?:number;
    Z?:number;
}